services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: formula-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3333
    ports:
      - '3000:3000'
